services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6377:6379"

volumes:
  data:
